#!/usr/bin/with-contenv bash

PATH=/sbin:/usr/sbin:/bin:/usr/bin
MOPIDY_EXEC="$(which mopidy)"
CONFIG_FILES="/usr/share/mopidy/conf.d:/etc/mopidy/mopidy.conf"

if [ -n "${UMASK_SET}" ] && [ -z "${UMASK}" ]; then
  echo -e "You are using a legacy method of defining umask\nplease update your environment variable from UMASK_SET to UMASK\nto keep the functionality after July 2021"
  umask ${UMASK_SET}
fi

exec s6-setuidgid abc /usr/local/bin/start-mopidy
